runtime: python311

entrypoint: gunicorn -b :$PORT server:app

env: standard

env_variables:
  FLASK_ENV: "production"
  BASEROW_TOKEN: "lx3pu0Jovlbaujjilm270IeMxdPbZTr4"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
